### ISSUE TITLE
Server Won't Start

### ISSUE THREAD

**Issue by cootshk** [wolveix/satisfactory-server#134] opened 2022-06-06 13:29 UTC
**Describe the Bug**
the server won't start

**Your Runtime Command or Docker Compose File**

```
sudo docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -v /home/______/Satisfactory:/config -p 7777:7777/udp -p 15000:15000/u
dp -p 15777:15777/udp wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**

```
===== START ISSUE REPORT =====
OS:  Linux ubuntuserverr720 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz
RAM: 10GB/15GB
HDD: 35GB/40GB (93% used)
===== END ISSUE REPORT =====
```

**Additional Context**

this seems to be the error:
Error! App '1690800' state is 0x202 after update job.

**Comment by wolveix** [comment] 2022-06-08 22:50
Hey! This is a duplicate of #131. You don't have enough diskspace to download the game files. Clear some space (you need to have ~10GB available).

**Closed by wolveix** 2022-06-08 22:50 UTC
