### ISSUE TITLE
Long Connection Times for Clients

### ISSUE THREAD

**Issue by Joinatic** [wolveix/satisfactory-server#7] opened 2021-05-12 15:04 UTC
Hi there,

we got huge connection times. We need 20+ minutes to connect. All of us made the game.ini etc. changes. The container is running on an 10 core 48GB RAM V-Server. 

docker-compose
```
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    environment:
        - STEAMUSER=***
        - STEAMPWD=***
        - STEAMCODE=***
    ports:
        - '7777:7777/udp'
    volumes:
        - '/var/docker/satisfactory/config/savefilebackups:/config/savefilebackups'
        - '/var/docker/satisfactory/config/savefiles:/config/savefiles'
        - '/var/docker/satisfactory/config/steam:/config/steam'
    restart: unless-stopped
```

is it a bug or did I miss any configuration? Removed gamefiles from volumes to be sure its not an sync problem.

**Comment by wolveix** [comment] 2021-05-12 15:08
Hi! Thanks for your feedback.

This is not an issue your end, and seems to be an issue with the game. I've encountered it with the server I'm running, though it eventually went away and/or only affected one or two people. Though the longest I've ever seen it take for someone to connect has been 5 minutes, certainly not 20+. I'd appreciate any logs that you could provide! You can grab the logs from the following path within the container:

```
cp "/home/satisfactory/.wine/drive_c/users/satisfactory/Local Settings/Application Data/FactoryGame/Saved/Logs/FactoryGame.log" /config/server.log
```

**Comment by wolveix** [comment] 2021-05-12 15:11
Also, I'd recommend changing the volumes you've listed, and instead mount the `/config` directory directly. Otherwise, the gamefiles will redownload on each container rebuild.

**Comment by Joinatic** [comment] 2021-05-12 16:03
`[2021.05.12-15.46.55:289][728]LogNet: Join succeeded: Flu ~`
Is now 17minutes ago and I am still loading. Here are the logs:

[server.log](https://github.com/wolveix/satisfactory-server/files/6467470/server.log)

**Comment by wolveix** [comment] 2021-05-12 16:09
Thanks for the logs, I'll admit there's not as much information there as I would have liked; not that that's your fault at all.

Just to confirm a couple of things: 

- Are you running the latest version of the Docker image?
- Are you using mods? If so, which mods? 
- Did you generate a save on your client and then put it into the server's save directory?

**Comment by Joinatic** [comment] 2021-05-12 16:13
- yes, latest version is installed
- no there are no mods installed
- yes the save game was prevoiusly used in multiplayer without a server.

**Comment by wolveix** [comment] 2021-05-12 16:51
Thanks for answering those questions. I just made a minor change to the repo which removes the "Host" ghost player. Please try updating the image on your end and see whether it makes a difference to your situation at all.

**Comment by Joinatic** [comment] 2021-05-12 18:32
It doesn't seem to make a different. I am trying to test it with the original save game that didn't run on a server already, but a Satisfactory update is killing my progress right now. I will post new informations if I got some, after updating the server.

**Comment by Joinatic** [comment] 2021-05-12 19:11
Update is done, and we are loading for 15min+ now. So it doesn't seem to make a difference.

**Comment by wolveix** [comment] 2021-05-12 19:17
Could you try generating a fresh save in your client and then running the server with that? Just trying to rule out the save file.

**Comment by Joinatic** [comment] 2021-05-12 19:23
It's loading instantly.. Is there a way to fix our savefile?

**Comment by wolveix** [comment] 2021-05-12 19:42
That's interesting! Could you upload your save file here so that I can take a look at it?

**Comment by Joinatic** [comment] 2021-05-12 19:56
sure here it is
[savefile.zip](https://github.com/wolveix/satisfactory-server/files/6468764/savefile.zip)

**Comment by Joinatic** [comment] 2021-05-12 20:58
I deleted all players and we cloud connect within 5 minutes. But the performance is horrible. We need to wait minutes until buildings are build. Sometimes it is build but not visible and the stats of buildings take extremly long to load.

**Comment by demonly** [comment] 2021-05-13 03:43
Same problem here. When I loading instantly, actually my character has entered the game. Ask someone in game kill my character, then I can enter the game.

**Comment by wolveix** [comment] 2021-05-14 10:38
Thanks for the feedback guys, I'll check out your save file shortly @Joinatic.

**Comment by wolveix** [comment] 2021-05-17 14:14
@Joinatic could you try stopping the server container, removing all files from the `/config/savefiles` directory (you might want to just `cp -rp` the directory to `/config/savefiles.old` or something), then placing the modified save file attached into that directory? I wasn't able to reproduce the issue you're describing when hosting your save on my server, but the modifications I made to your save might have made a difference.

[savefile_modified.zip](https://github.com/wolveix/satisfactory-server/files/6494367/savefile_modified.zip)

**Comment by wolveix** [comment] 2021-05-17 14:28
@demonly @Joinatic It appears that this is specifically a bug with Satisfactory Update 4, and is not an issue with this server implementation. So unfortunately, I won't be able to resolve the issue as it's not on my end. My recommendation for when it happens, is to use a site like [Satisfactory Calculator](https://satisfactory-calculator.com/en/interactive-map) and delete all ghost "guest" players (they have an empty inventory).

**Comment by Joinatic** [comment] 2021-05-20 10:38
Doesn't seem to make a difference. The connection time can be lowered by deleting the own char in a savegame editor. But playing on a server with 4 players seems to be impossible. We are using the server currently only for generating ress. If we want to play we download the save game and host it locally with integrated koop. Maybe its a general problem with the dedicated server?

**Comment by wolveix** [comment] 2021-05-20 10:43
It's been confirmed that it's an issue with Update 4 and not the server. Unfortunately, since a few recent commits, I'm totally unable to reproduce the issue that you're experiencing. I've had 6 people playing on my server with no issues at all.

Until I'm able to reproduce the issue, I'm unfortunately unable to diagnose the issue further. Could you confirm that you've run `docker-compose pull && docker-compose up -d` to update to the latest version?

**Comment by Joinatic** [comment] 2021-05-23 11:01
yes I did. And even if I'm solo playing on the server it needs some seconds to display the inventory of a container for example. It takes longer with every player joining the server. Also tested a Zap-Hosting server and uploaded our save game.. it works perfect. No long loading and no delay at containers and factories. Maybe my server isn't strong enough or something.. I dont know. :(

**Comment by wolveix** [comment] 2021-05-23 11:06
@Joinatic my game world is further along than yours is and is coping fine on a 2 core, 2GB RAM server. Even with 6 players, everything is near instant. I can appreciate that it seems to work fine via other implementations; however, until I'm given a save where I can re-produce the issue, there's not a lot that I can do. As are able to produce the issue, you're more than welcome to look over the repo and submit a pull request to resolve the issue.

**Comment by wolveix** [comment] 2021-08-06 11:45
@Joinatic I've had much better success with my users recently. Have you had a chance to try this recently at all?

**Comment by wolveix** [comment] 2021-08-09 15:56
I'm going to close this for the time being as I believe the issue has been resolved within the game. Please feel free to re-open @joinatic if you continue experiencing the issue.

**Closed by wolveix** 2021-08-09 15:56 UTC
Labels: game bug
