### ISSUE TITLE
Error! App '1690800' state is 0x6 after update job.

### ISSUE THREAD

**Issue by Felrenzler** [wolveix/satisfactory-server#377] opened 2024-12-03 22:48 UTC
### Describe the Bug

Game is not updating from steam 

satisfactory-server  | Downloading the latest version of the game...
satisfactory-server  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | Logging directory: '/home/steam/.steam/steam/logs'
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Verifying installation...
satisfactory-server  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1731433425
satisfactory-server  | -- type 'quit' to exit --
satisfactory-server  | Loading Steam API...OK
satisfactory-server  |
satisfactory-server  | Connecting anonymously to Steam Public...OK
satisfactory-server  | Waiting for client config...OK
satisfactory-server  | Waiting for user info...OK
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  | Error! App '1690800' state is 0x6 after update job.

### Your Runtime Command or Docker Compose File

Please censor anything sensitive. Your runtime command might look like this:

Standard docker compose as listed on the docker page.

### Debug Output

satisfactory-server  | Current version:
satisfactory-server  | 1.8.8
satisfactory-server  | Current user:
satisfactory-server  | uid=0(root) gid=0(root) groups=0(root)
satisfactory-server  | Proposed user:
satisfactory-server  | uid=1000(?) gid=1000(?) groups=1000(?)
satisfactory-server  |
satisfactory-server  | Exiting...
satisfactory-server  |
satisfactory-server  | System info:
satisfactory-server  | OS:  Linux satisfactory-server 5.10.0-33-amd64 #1 SMP Debian 5.10.226-1 (2024-10-03) x86_64 x86_64 x86_64 GNU/Linux
satisfactory-server  | CPU: Intel Core Processor (Haswell, no TSX, IBRS)
satisfactory-server  | RAM: 23GB/23GB
satisfactory-server  | HDD: 11GB/97GB (12% used)

Started with the first fiscmas patch the last week of november.  Can resolve by removing the gamefiles directory and forcing a fresh download.  Then this patch hit and same issue.  Game is downloading the update, the application of the update says it's okay, then we have that error pop up and the container keeps restarting.

[+] Running 1/1
 ✔ Container satisfactory-server  Recreated                                                                                                                                     0.1s
Attaching to satisfactory-server
satisfactory-server  | ===== Satisfactory Server 1.8.8 =====
satisfactory-server  | https://github.com/wolveix/satisfactory-server
satisfactory-server  |
satisfactory-server  | Checking available memory: 23GB detected
satisfactory-server  | Clearing old Satisfactory logs (set LOG=true to disable this)
satisfactory-server  | Setting autosave number to 5
satisfactory-server  | Setting max objects to 2162688
satisfactory-server  | Setting max tick rate to 30
satisfactory-server  | Setting server streaming to 1
satisfactory-server  | Setting timeout to 30
satisfactory-server  | Setting max players to 4
satisfactory-server  | Checking available storage: 80GB detected
satisfactory-server  |
satisfactory-server  | Downloading the latest version of the game...
satisfactory-server  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
satisfactory-server  | [  0%] Checking for available update...
satisfactory-server  | [----] Downloading update (0 of 48,188 KB)...
satisfactory-server  | [  0%] Downloading update (0 of 48,188 KB)...
satisfactory-server  | [  0%] Downloading update (0 of 48,188 KB)...
satisfactory-server  | [  0%] Downloading update (1,163 of 48,188 KB)...
satisfactory-server  | [  2%] Downloading update (2,829 of 48,188 KB)...
satisfactory-server  | [  5%] Downloading update (4,489 of 48,188 KB)...
satisfactory-server  | [  9%] Downloading update (6,142 of 48,188 KB)...
satisfactory-server  | [ 12%] Downloading update (7,538 of 48,188 KB)...
satisfactory-server  | [ 15%] Downloading update (8,697 of 48,188 KB)...
satisfactory-server  | [ 18%] Downloading update (9,730 of 48,188 KB)...
satisfactory-server  | [ 20%] Downloading update (10,764 of 48,188 KB)...
satisfactory-server  | [ 22%] Downloading update (11,892 of 48,188 KB)...
satisfactory-server  | [ 24%] Downloading update (12,955 of 48,188 KB)...
satisfactory-server  | [ 26%] Downloading update (13,981 of 48,188 KB)...
satisfactory-server  | [ 29%] Downloading update (15,015 of 48,188 KB)...
satisfactory-server  | [ 31%] Downloading update (16,186 of 48,188 KB)...
satisfactory-server  | [ 33%] Downloading update (17,205 of 48,188 KB)...
satisfactory-server  | [ 35%] Downloading update (18,252 of 48,188 KB)...
satisfactory-server  | [ 37%] Downloading update (19,358 of 48,188 KB)...
satisfactory-server  | [ 40%] Downloading update (20,415 of 48,188 KB)...
satisfactory-server  | [ 42%] Downloading update (21,462 of 48,188 KB)...
satisfactory-server  | [ 44%] Downloading update (22,599 of 48,188 KB)...
satisfactory-server  | [ 46%] Downloading update (23,613 of 48,188 KB)...
satisfactory-server  | [ 49%] Downloading update (24,654 of 48,188 KB)...
satisfactory-server  | [ 51%] Downloading update (25,698 of 48,188 KB)...
satisfactory-server  | [ 53%] Downloading update (26,803 of 48,188 KB)...
satisfactory-server  | [ 55%] Downloading update (27,875 of 48,188 KB)...
satisfactory-server  | [ 57%] Downloading update (28,896 of 48,188 KB)...
satisfactory-server  | [ 59%] Downloading update (30,046 of 48,188 KB)...
satisfactory-server  | [ 62%] Downloading update (31,075 of 48,188 KB)...
satisfactory-server  | [ 64%] Downloading update (32,091 of 48,188 KB)...
satisfactory-server  | [ 66%] Downloading update (33,210 of 48,188 KB)...
satisfactory-server  | [ 68%] Downloading update (34,265 of 48,188 KB)...
satisfactory-server  | [ 71%] Downloading update (35,253 of 48,188 KB)...
satisfactory-server  | [ 73%] Downloading update (36,288 of 48,188 KB)...
satisfactory-server  | [ 75%] Downloading update (37,374 of 48,188 KB)...
satisfactory-server  | [ 77%] Downloading update (38,352 of 48,188 KB)...
satisfactory-server  | [ 79%] Downloading update (39,359 of 48,188 KB)...
satisfactory-server  | [ 81%] Downloading update (40,426 of 48,188 KB)...
satisfactory-server  | [ 83%] Downloading update (41,348 of 48,188 KB)...
satisfactory-server  | [ 85%] Downloading update (41,826 of 48,188 KB)...
satisfactory-server  | [ 86%] Downloading update (42,320 of 48,188 KB)...
satisfactory-server  | [ 87%] Downloading update (42,851 of 48,188 KB)...
satisfactory-server  | [ 88%] Downloading update (43,324 of 48,188 KB)...
satisfactory-server  | [ 89%] Downloading update (43,816 of 48,188 KB)...
satisfactory-server  | [ 90%] Downloading update (44,333 of 48,188 KB)...
satisfactory-server  | [ 92%] Downloading update (44,806 of 48,188 KB)...
satisfactory-server  | [ 92%] Downloading update (45,298 of 48,188 KB)...
satisfactory-server  | [ 94%] Downloading update (45,821 of 48,188 KB)...
satisfactory-server  | [ 95%] Downloading update (46,296 of 48,188 KB)...
satisfactory-server  | [ 96%] Downloading update (46,777 of 48,188 KB)...
satisfactory-server  | [ 97%] Downloading update (47,300 of 48,188 KB)...
satisfactory-server  | [ 98%] Downloading update (47,789 of 48,188 KB)...
satisfactory-server  | [ 99%] Downloading update (48,188 of 48,188 KB)...
satisfactory-server  | [100%] Download Complete.
satisfactory-server  | [----] Applying update...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Cleaning up...
satisfactory-server  | [----] Update complete, launching...
satisfactory-server  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | Logging directory: '/home/steam/.steam/steam/logs'
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Verifying installation...
satisfactory-server  | [  0%] Downloading update...
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Download complete.
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Extracting package...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Installing update...
satisfactory-server  | [----] Cleaning up...
satisfactory-server  | [----] Update complete, launching Steamcmd...
satisfactory-server  | steamcmd.sh[38]: Restarting steamcmd by request...
satisfactory-server  | UpdateUI: skip show logoRedirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | Logging directory: '/home/steam/.steam/steam/logs'
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Verifying installation...
satisfactory-server  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1731433425
satisfactory-server  | -- type 'quit' to exit --
satisfactory-server  | Loading Steam API...OK
satisfactory-server  |
satisfactory-server  | Connecting anonymously to Steam Public...OK
satisfactory-server  | Waiting for client config...OK
satisfactory-server  | Waiting for user info...OK
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  | Error! App '1690800' state is 0x6 after update job.
satisfactory-server exited with code 0
satisfactory-server  | Checking available memory: 23GB detected
satisfactory-server  | Clearing old Satisfactory logs (set LOG=true to disable this)
satisfactory-server  | Setting autosave number to 5
satisfactory-server  | Setting max objects to 2162688
satisfactory-server  | Setting max tick rate to 30
satisfactory-server  | Setting server streaming to 1
satisfactory-server  | Setting timeout to 30
satisfactory-server  | Setting max players to 4
satisfactory-server  | Checking available storage: 80GB detected
satisfactory-server  |
satisfactory-server  | Downloading the latest version of the game...
satisfactory-server  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | Logging directory: '/home/steam/.steam/steam/logs'
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Verifying installation...
satisfactory-server  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1731433425
satisfactory-server  | -- type 'quit' to exit --
satisfactory-server  | Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 55 msec
satisfactory-server  | OK
satisfactory-server  |
satisfactory-server  | Connecting anonymously to Steam Public...OK
satisfactory-server  | Waiting for client config...OK
satisfactory-server  | Waiting for user info...OK
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  | Error! App '1690800' state is 0x6 after update job.
satisfactory-server  | Checking available memory: 23GB detected
satisfactory-server  | Clearing old Satisfactory logs (set LOG=true to disable this)
satisfactory-server  | Setting autosave number to 5
satisfactory-server  | Setting max objects to 2162688
satisfactory-server  | Setting max tick rate to 30
satisfactory-server  | Setting server streaming to 1
satisfactory-server  | Setting timeout to 30
satisfactory-server  | Setting max players to 4
satisfactory-server  | Checking available storage: 80GB detected
satisfactory-server  |
satisfactory-server  | Downloading the latest version of the game...
satisfactory-server  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | Logging directory: '/home/steam/.steam/steam/logs'
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Verifying installation...
satisfactory-server  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1731433425
satisfactory-server  | -- type 'quit' to exit --
satisfactory-server  | Loading Steam API...OK
satisfactory-server  |
satisfactory-server  | Connecting anonymously to Steam Public...OK
satisfactory-server  | Waiting for client config...OK
satisfactory-server  | Waiting for user info...OK
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  | Error! App '1690800' state is 0x6 after update job.
satisfactory-server  | Checking available memory: 23GB detected
satisfactory-server  | Clearing old Satisfactory logs (set LOG=true to disable this)
satisfactory-server  | Setting autosave number to 5
satisfactory-server  | Setting max objects to 2162688
satisfactory-server  | Setting max tick rate to 30
satisfactory-server  | Setting server streaming to 1
satisfactory-server  | Setting timeout to 30
satisfactory-server  | Setting max players to 4
satisfactory-server  | Checking available storage: 80GB detected
satisfactory-server  |
satisfactory-server  | Downloading the latest version of the game...
satisfactory-server  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-server  | Logging directory: '/home/steam/.steam/steam/logs'
satisfactory-server  | [  0%] Checking for available updates...
satisfactory-server  | [----] Verifying installation...
satisfactory-server  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1731433425
satisfactory-server  | -- type 'quit' to exit --
satisfactory-server  | Loading Steam API...OK
satisfactory-server  |
satisfactory-server  | Connecting anonymously to Steam Public...OK
satisfactory-server  | Waiting for client config...OK

**Comment by aceawd** [comment] 2024-12-03 23:02
lurking as I'm getting this exact same error just now. 

Server has been working great. Saw there was a Steam update so went to redeploy the container and then it kept crash looping with the same '0x6' error. Tons of space on the drive, no issues reaching the internet, not sure what's up.

**Comment by namaku** [comment] 2024-12-03 23:25
I got the same error on the latest update.

**Comment by wolveix** [comment] 2024-12-04 12:06
Duplicate of #371 and #374. It's the pinned issue. Once again, this is a SteamCMD issue.

**Closed by wolveix** 2024-12-04 12:06 UTC

**Comment by Navok85** [comment] 2024-12-08 14:06
Even this thread is close, here a some additional informations

It looks like Valve are removing all sorts of dedicated servers from anonymous login. No idea why currently. If anyone has any ideas feel free to let us know https://steamdb.info/sub/17906/history/

Satisfactory is mentioned in https://steamdb.info/changelist/26374539/
