### ISSUE TITLE
Server RAM Usage and Client Connection Timeout

### ISSUE THREAD

**Issue by IMarkoMC** [wolveix/satisfactory-server#143] opened 2022-09-20 23:39 UTC
**Describe the Bug**
When i try joining the game, the server ram jumps from ~2GB to ~7GB (It used less than 5gb earlier) 
The server gives a lot of errors like 
```
[2022.09.20-23.25.55:491][784]LogNavigationDirtyArea: Warning: Skipping dirty area creation because of empty bounds (object: FoliageInstancedStaticMeshComponent /Game/FactoryGame/Map/GameLevel01/Tile_X5_Y1.Tile_X5_Y1:PersistentLevel.InstancedFoliageActor_0.FoliageInstancedStaticMeshComponent_283)

```
The client gives a timeout error while those errors are happening.
![image](https://user-images.githubusercontent.com/44303652/191383151-7a4c38ae-5dfd-42fb-9f82-2631f31ac2eb.png)

**Your Runtime Command or Docker Compose File**
Started it with the command provided in this repo to rule out some things
```
docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -v /path/to/config:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux ubuntu 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
RAM: 10GB/11GB
HDD: 33GB/109GB (32% used)
===== END ISSUE REPORT =====
```

**Additional Context**
[Entire server log](https://github.com/wolveix/satisfactory-server/files/9611851/Serverlog.log)

**Comment by silentnyte** [comment] 2022-09-21 14:05
I am having similar issues using the truecharts helm instance.

**Comment by Kadigan** [comment] 2022-09-21 14:52
Could you check if you can connect after the server has actually finished loading the game?

**Comment by IMarkoMC** [comment] 2022-09-21 15:22
> Could you check if you can connect after the server has actually finished loading the game?

You can connect once it gives up all of the errors and the memory stops going up but it runs weird.
Combat is broken (movement is glitched https://streamable.com/b97n7g ) and the game itself feels weird

**Comment by MattsBos** [comment] 2022-09-21 15:25
So, you are now connected fine as you are in game?

The glitchy thing is a new bug introduced, will have to be fixed by Satisfactory, that happens with the spitters for everyone this update.

**Comment by IMarkoMC** [comment] 2022-09-21 15:30
> Also, the mention of RAM is as designed, Satisfactory Update 6 dedicated server requires 12GB of RAM.

12GB of ram a satisfactory server? For 2 players no way
It ran flawlessly with 6gb earlier on that's 2x the memory.

I guess I'll stop playing the game until the memory is reduced lol

> So, you are now connected fine as you are in game?
If you wait the 5 minutes it takes to load and give all that errors it kinda works. 
It's not the same as it worked before, the game runs weird even with enemies not targeting you properly. That might be because it's nearly out of memory but i refuse to give a single server 12G of ram for 2 users

**Comment by MattsBos** [comment] 2022-09-21 15:33
Yeah, it's quite a big change, but it's been introduced ever since Update 6 hit experimental. 12GB is the new requirement. My server is currently using 11.4GB and it's just me in there. I don't think player count matters as it stays roughly the same with 4 players active.

**Comment by IMarkoMC** [comment] 2022-09-21 15:35
Well time to shut down the server, get a way to downgrade to update 5 and wait until the memory usage goes back to something normal aka <6GB

Even Minecraft eats less memory with more users

**Comment by wolveix** [comment] 2022-09-21 15:35
Yeah, it sounds like a memory leak or a bug introduced with the update. Just wait until it's resolved :) Not a lot we can do in the meantime unfortunately!

**Comment by Kadigan** [comment] 2022-09-21 15:37
> You can connect once it gives all of the errors and the memory stops going
So - user error: you tried connecting before the server was ready to accept connections.

> Combat is broken (movement is glitched https://streamable.com/b97n7g )
My suspicion is that this is due to the projectile the spitter throws at you. The effect is similar to going through other world objects, and the bug is similar to the whole boulder & hatcher issue (where you'd get weird jerking around when you go through areas these things _used to be in_, but no longer are). Regardless, that's a game issue, not a networking/connectivity issue.

> and the game itself feels weird
... I'm not sure how to understand that one, to be honest.

> I'm in the same network as the server is, that's not a weird networking issue between a remote server and the client
You're correct, it's not.

**Comment by IMarkoMC** [comment] 2022-09-21 15:38
Kinda sad seeing that in all this time nothing changed in how they handle updates. 
Update news: Added new bugs and new memory leaks

**Comment by Kadigan** [comment] 2022-09-21 15:42
> get a way to downgrade to update 5

As far as I'm aware, that's not something that's been made available. You would need to fetch an older codebase, for both client and server.

> wait until the memory usage goes back to something normal aka <6GB

Not sure where you get those numbers - my EA Update 5 ran between 6.7 and 7.8 GiB (Linux x64).

Regardless: the developers are aware that the server requires more RAM, and they say it's related to all of the changes that have been made to it over the course of Update 6 development. While it will likely go down somewhat, I honestly do not expect it will go below 9 GiB. Considering that the game is still in development, and how RAM-hungry UE games are - I rather expect it to go _up_.

> Even Minecraft eats less memory with more users

That may be so. This isn't Minecraft, however. HLDS used 50 MiB of RAM, you know? I wish we could go back to _that._

**Comment by Kadigan** [comment] 2022-09-21 15:42
> Some enemies are dumb and they just sit there from time to time (They target the user for a moment and then they sit still)

Update 6 introduced a substantial rewrite of enemy AI. I suspect it's related to that, and will see future work.

**Comment by IMarkoMC** [comment] 2022-09-21 15:43
> Not sure where you get those numbers - my EA Update 5 ran between 6.7 and 7.8 GiB (Linux x64).

I was playing with 2 friends less than a week ago and it was using 5 - 5.7gb (capped at that 6GB)

**Comment by Kadigan** [comment] 2022-09-21 15:44
> I was playing with 2 friends less than a week ago and it was using 5 - 5.7gb (capped at that 6GB)

Where did you get those numbers? Can you provide a command?

And I assume if it goes beyond the cap, it'll just OOM?

**Comment by IMarkoMC** [comment] 2022-09-21 15:48
> Where did you get those numbers? Can you provide a command?

There's a public Pterodactyl panel egg. I was using that one before all of this happened [this](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/satisfactory)

> And I assume if it goes beyond the cap, it'll just OOM?

Never went OOM for me in more than a month

**Comment by IMarkoMC** [comment] 2022-09-21 15:50
> I honestly do not expect it will go below 9 GiB. Considering that the game is still in development, and how RAM-hungry UE games are - I rather expect it to go up.

If using 9+GiB for a game server for the developers of the game is ""normal"" we have some big issues going forward

**Comment by Kadigan** [comment] 2022-09-21 15:51
> There's a public Pterodactyl panel egg

Unfortunately, I have no clue how to use that. Can you tell me where Pterodactyl gets this memory reading from? Because, like I said, I'm getting completely different readings from basic tools like `top`/`htop`, `ps` etc.

**Comment by IMarkoMC** [comment] 2022-09-21 15:52
> Unfortunately, I have no clue how to use that. Can you tell me where Pterodactyl gets this memory reading from? Because, like I said, I'm getting completely different readings from basic tools like top/htop, ps etc.

HTOP reported the same memory usage as the panel i wish i had some screenshot but i dont

**Comment by Kadigan** [comment] 2022-09-21 15:52
> If using 9+GiB for a game server for the developers of the game is ""normal"" we have some big issues going forward

Sadly, this is the world we now live in. ARK servers with a number of mods loaded in range from 13 to 18 GiB of RAM, and it doesn't look like this will go down any time soon (ARK is another example of a UE game). Similarly, CONAN Exiles - about 12-14 GiB (another UE game).

**Comment by Kadigan** [comment] 2022-09-21 15:55
> HTOP reported the same memory usage as the panel i wish i had some screenshot but i dont

Which value are you using as a reference?

**Comment by IMarkoMC** [comment] 2022-09-21 15:55
I'll just stop playing the game again until they get the memory usage to a reasonable number. 
Well, time to wait i guess

**Comment by Kadigan** [comment] 2022-09-21 15:56
> I'll just stop playing the game again until they get the memory usage to a reasonable number. Well, time to wait i guess

Like I said - I fully expect the requirement to - it not grow - then at least remain basically where it is. So, I assume you're done with the game, on principle.

**Comment by Kadigan** [comment] 2022-09-21 15:59
Yeah, that doesn't really help, as there's a number of performance metrics it might be referencing. I'm sourcing my information from the "resident memory" metric of the executable. Where is Pterodactyl sourcing it, that it can display _a lower value?_

**Comment by IMarkoMC** [comment] 2022-09-21 16:07
> Yeah, that doesn't really help, as there's a number of performance metrics it might be referencing. I'm sourcing my information from the "resident memory" metric of the executable. Where is Pterodactyl sourcing it, that it can display a lower value?

If you want specifics about that, the developers of the panel should be able to answer that. It's the same reported in docker stats 
![image](https://user-images.githubusercontent.com/44303652/191555235-b59fcd3d-1862-4688-a2c3-9c8cd836525c.png)
 but idk from where they take it

> And how does it report 6.44 GB of disk, when I know for a fact that the game takes up a little over 7 GiB?

The folder now is 7.0G according to `` du -sh`` and it's reporting 6.95 GB. Not something that worries me

**Comment by Kadigan** [comment] 2022-09-21 16:13
> 7.65 GiB

Now that is _much more in-line_ with what I've been seeing. And since Docker doesn't actually spin up a separate OS, it should be limited mostly to what the application is using.

So, unless this was a report from a different point in time (or a different server version), that 5.41 GiB reported memory use is _bogus._

**Comment by IMarkoMC** [comment] 2022-09-21 16:16
> Now that is _much more in-line_ with what I've been seeing. And since Docker doesn't actually spin up a separate OS, it should be limited mostly to what the application is using.

That's the memory that it's using now.

The 5.4GB was the 17 of September.

**Comment by Kadigan** [comment] 2022-09-21 16:18
> Anyways this is not going anywhere

You're right. I went ahead and asked in Pterodactyl Discord - they should be qualified to clear up any misunderstandings I have.

**Comment by Kadigan** [comment] 2022-09-21 16:20
> > It's a game bug, not a user error

The fact that you tried connecting before the server was ready to accept connections **is user error**. Every other aspect of the reported issue is unrelated to the reported problem.

**Comment by IMarkoMC** [comment] 2022-09-21 16:21
> The fact that you tried connecting before the server was ready to accept connections **is user error**. Every other aspect of the reported issue is unrelated to the reported problem.

I didn't try connecting before the server was ready to accept connections, i can leave it for 15 minutes and it will do nothing until i try connecting. 

Anyways this is pointless

**Comment by wolveix** [comment] 2022-09-21 17:19
@IMarkoMC to clarify, are you still experiencing the issue? I'd like to keep this issue open if so, as I suspect others may try to open related issues.

**Comment by wolveix** [comment] 2022-09-21 17:21
Also, lets keep things civil please guys :) If the game server was accepting connections prior to the save being loaded, that is a design flaw mixed with user error in my opinion. If the issue is still happening regardless of how much time has been left, as @IMarkoMC is reporting, then it's clear that there is in fact a bug with the game server itself.

**Comment by wolveix** [comment] 2022-09-21 17:22
> Also, the mention of RAM is as designed, Satisfactory Update 6 dedicated server requires 12GB of RAM.

@MattsBos that's interesting, I wonder when/why they changed that? The game server (update 4 & 5) needed half of that.

**Comment by wolveix** [comment] 2022-09-21 17:31
@IMarkoMC @silentnyte @Kadigan @MattsBos I've pushed a commit which checks the server's available RAM on startup to be in-line with the server's new minimum RAM requirements.

**Comment by IMarkoMC** [comment] 2022-09-21 17:32
> to clarify, are you still experiencing the issue? I'd like to keep this issue open if so, as I suspect others may try to open related issues.

Yes. The server is still loading the world once you try connecting and the client timeouts.

I just restarted it to check. Started the server waited 5 minutes until joining (no logs meanwhile) and the same thing happens

**Comment by wolveix** [comment] 2022-09-21 17:41
@IMarkoMC due to the new RAM requirements, I believe this is unfortunately a case of your system not being powerful enough to run the game server. I don't really understand why CSS have doubled the minimum RAM requirement, but unfortunately it's out of my control.

**Comment by wolveix** [comment] 2022-09-21 17:43
@IMarkoMC the minimum requirement is 12GB, your system appears to have 11GB.

**Comment by IMarkoMC** [comment] 2022-09-21 17:44
> @IMarkoMC the minimum requirement is 12GB, your system appears to have 11GB

It's not using nearly 11GB of ram. But let me move it to another server and test it, i don't expect any changes

**Comment by wolveix** [comment] 2022-09-21 17:46
@IMarkoMC I appreciate that, but it's the minimum requirement. As you're experiencing issues, it's reasonable to assume that your lack of available memory could be the cause :) The game could be failing to load something, preventing further memory allocation. Please try it on another server as you've suggested and let us know how you get on

**Comment by MattsBos** [comment] 2022-09-21 17:54
> > Also, the mention of RAM is as designed, Satisfactory Update 6 dedicated server requires 12GB of RAM.
> 
> @MattsBos that's interesting, I wonder when/why they changed that? The game server (update 4 & 5) needed half of that.

The very first release of Update 6 on the experimental branch came with a considerable rewrite and update (even though it looks like a small update) causing the new requirements. Everyone hopes this will be changed/optimized, but considering the stability it brings and how good the server runs now I think it's for the better. RAM is cheap, but the simple hobbyist self-hosts on old systems will have some issues with the higher RAM requirement.

Ever since Update 6, the servers I have running are using 11+GB in memory, regardless of connected players or size of the save game. Limiting this manually will cause issues sooner or later. In hibernation the memory usage is around 3GB max. Soon as 1 player connects it will jump to 11GB.

This very update was rolled out to Early Access just a few days ago, I expect a lot more people to find memory problems.

Also, I don't know why Marko is claiming/seeing such low values and why that would even work on the previous Update 5. As I cannot replicate any of that and don't see people with that low memory in any of the Discord servers (both Pterodactyl and official Satisfactory) I'm in.

To close off, I don't understand how you fetched that ingame footage if you can't connect to your server. Did you just get that from the internet somewhere or did you actually manage to connect to your server eventually, as in your first message you say it doesn't work, then later you say you got in and then again you say it was impossible.

**Comment by IMarkoMC** [comment] 2022-09-21 17:58
> To close off, I don't understand how you fetched that ingame footage if you can't connect to your server. Did you just get that from the internet somewhere or did you actually manage to connect to your server eventually, as in your first message you say it doesn't work, then later you say you got in and then again you say it was impossible.

if you try connecting once, it kicks timeouts, i waited a few minutes and tried again once the server finished giving errors and i was able to get in

> Also, I don't know why Marko is claiming/seeing such low values and why that would even work on the previous Update 5

I have a bunch of friends that hosted satisfactory prior to update 6 and they never used more then 6gb, limiting the ram shouldn't make the game not work as it didn't do earlier on

**Comment by wolveix** [comment] 2022-09-21 18:07
> The very first release of Update 6 on the experimental branch came with a considerable rewrite and update (even though it looks like a small update) causing the new requirements. Everyone hopes this will be changed/optimized, but considering the stability it brings and how good the server runs now I think it's for the better. RAM is cheap, but the simple hobbyist self-hosts on old systems will have some issues with the higher RAM requirement.

@MattsBos thank you so much for the information! I haven't been following Update 6 too closely, so I was completely unaware of the internal changes.

> I have a bunch of friends that hosted satisfactory prior to update 6 and they never used more then 6gb, limiting the ram shouldn't make the game not work as it didn't do earlier on and it's not using 100% of that

@IMarkoMC right, because pre-Update 6 had a much lower RAM requirement. The behaviour you're experiencing makes sense given the new requirements.

**Comment by IMarkoMC** [comment] 2022-09-21 18:14
> @IMarkoMC right, because pre-Update 6 had a much lower RAM requirement. The behaviour you're experiencing makes sense given the new requirements.

It's doing the same with 32GB of ram (World not loading until you join, a lot of errors and the client ends up timeouting).

You need to rejoin after that to play

https://www.youtube.com/watch?v=04EeCmPK8MI

Skip to 3:14 if you don't want to see 3 minutes of the server doing nothing

**Comment by MattsBos** [comment] 2022-09-21 18:39
I just watched the video, what instantly gets my attention is that the process of starting up the server and then the process of actually loading the map when you connect is taking absolute ages. 

I just double checked my times to verify:
- Starting the server takes 12 seconds to complete
- First player connecting to fresh server takes 20 seconds to complete.

Keep in mind that most timers in Satisfactory are set for 30 seconds, that's also what the error tells you in the client, the connection timed out. Judging by your video, it just seems like your server isn't fast enough to load everything within that time window, the server does not send info to the client to keep alive, so the client disconnects as it didn't receive data for 30 seconds. This again explains why the second time it does work, because the server finished loading the map in the meantime.

Your server is the bottleneck and does not have enough performance to be ready within 30 seconds. This makes it all very clear, thanks for the video!

Just a quick visit back to the 11GB RAM if you want to go back to that, your server will use more than that over time, I have never seen it go over 12GB though. But 11GB will fail eventually, even if you get it up and running.

**Comment by IMarkoMC** [comment] 2022-09-21 18:47
> Keep in mind that most timers in Satisfactory are set for 30 seconds, that's also what the error tells you in the client, the connection timed out. Judging by your video, it just seems like your server isn't fast enough to load everything within that time window, the server does not send info to the client to keep alive, so the client disconnects as it didn't receive data for 30 seconds. This again explains why the second time it does work, because the server finished loading the map in the meantime.

Interesting, has that changed in the update 6? because i didn't had any issues earlier on

**Comment by MattsBos** [comment] 2022-09-21 18:52
No, there's just more data to load, so this is probably just pushing your over the edge. In Update 5 the memory usage is half of update 6 so you would only need half the time to load the map on the server. Maybe that was just within limits in Update 5.

Look at your video when you join, you can see the server working, loading everything into memory and you disconnect when it's around 6-7GB memory while it has to go to around 10.xGB to be ready and accept players. And that amount would just fit the time window for Update 5, but not for 6.

**Comment by Kadigan** [comment] 2022-09-22 20:17
> @MattsBos that's interesting, I wonder when/why they changed that? The game server (update 4 & 5) needed half of that.

Not so. Update 5 required 8 GB of RAM, so not quite half. This change happened with Update 6.

**Comment by Kadigan** [comment] 2022-09-22 20:18
> It's doing the same with 32GB of ram (World not loading until you join, a lot of errors and the client ends up timeouting).
> You need to rejoin after that to play

I've tested some things, and I've been able to replicate your server's behaviour: the server will delay loading the save if the option **"Pause the game when no players are connected"** is enabled. With that option enabled, it will delay loading the world until it actually needs to (i.e. a player connects).

**Comment by IMarkoMC** [comment] 2022-09-22 22:59
@wolveix feel free to lock this issue as it's not something that someone can fix. I'll wait and see what the game devs do, 
Sorry for wasting your time.

Thanks for the info @MattsBos

**Comment by wolveix** [comment] 2022-09-23 20:42
I'm going to re-open this because people keep opening new issues. For anyone new that ends up here, this is a known bug with the game server. Please read through this issue, as well as #144. You can see the bug report here:

https://questions.satisfactorygame.com/post/632d2441ca608e080351fb69

Thanks :)

**Comment by kAuFish** [comment] 2022-09-27 13:48
What should be at the end of my server log if it has loaded "correctly" and no player has joined yet. Getting a similar timeout issue but my logs never update.

**Comment by IMarkoMC** [comment] 2022-09-29 16:39
> What should be at the end of my server log if it has loaded "correctly" and no player has joined yet. Getting a similar timeout issue but my logs never update.

You can disable Pause the game when no players are connected and just let the game run 24/7 and it should work, or you can join once, wait until the console stops showing new lines and then join again, looking at the memory usage can also tell you when to join

**Comment by kAuFish** [comment] 2022-10-15 22:10
@IMarkoMC Sorry for the late reply, but while that did initially help, after awhile trying to use the save my friends I had created eventually caused the same issue on starting the container. My guess is that the world we had eventually went over all 12GB of ram dedicated to it as the loading console messages just never seemed to end. I've given up on playing the game since.

**Comment by silentnyte** [comment] 2022-10-17 12:14
So after a few weeks of playing and constantly fighting to get connected (sometimes it would take me over 30 mins) I decided to try running the dedicated server on another machine. Here is the crazy part the second machine a 10 year old Mac Mini with a slower mobile CPU and less RAM runs the server great. If I wait 1 minute to join the game, I connect every time. No fight. In both cases I am only running satisfactory on the machine, nothing else.

First server:
Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz w/ 24Gb of RAM running TrueNAS Scale

Second server:
Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz w/ 16Gb RAM running TrueNAS Scale

**Closed** 2022-12-07 20:14 UTC
Labels: game bug
