### ISSUE TITLE
Server won't start anymore with latest image

### ISSUE THREAD

**Issue by shaguarger** [wolveix/satisfactory-server#18] opened 2021-07-28 19:59 UTC
Hi @wolveix, thanks for the great work! 

Your Satisfactory image ran smooth until yesterday. After over 2 weeks my server won't start anymore. It crashed soon after I fell down and should have died, but didn't. I stopped the server, saw that you made 2 commits, pulled and started. Since then this happens:

```
satisfactory-server    | Checking available space...
satisfactory-server    | Downloading the latest version of the game...
satisfactory-server    | Redirecting stderr to '/root/.steam/logs/stderr.txt'
satisfactory-server    | Looks like steam didn't shutdown cleanly, scheduling immediate update check
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | [----] Verifying installation...
satisfactory-server    | Steam Console Client (c) Valve Corporation
satisfactory-server    | -- type 'quit' to exit --
satisfactory-server    | Loading Steam API...OK
satisfactory-server    | @sSteamCmdForcePlatformType windows
satisfactory-server    | "@sSteamCmdForcePlatformType" = "windows"
satisfactory-server    | Logging in user 'xxx' to Steam Public...OK
satisfactory-server    | Waiting for client config...OK
satisfactory-server    | Waiting for user info...OK
satisfactory-server    | force_install_dir /config/gamefiles
satisfactory-server    | app_update "526870"
satisfactory-server    | Success! App '526870' already up to date.
satisfactory-server    | quit
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
```

I tried restarting and removing data. I ended up with only the savefile.sav and the docker-compose.yml

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        volumes:
            - './config:/config'
        restart: unless-stopped
```

Sadly there is only the `latest` tag so I can't check if it's an issue with the image.

Any ideas?

PS.: The savefile does load on another server with the latest image.

**Comment by wolveix** [comment] 2021-07-28 20:11
Hey! Glad to hear that you're enjoying the project :) 

Hm, that looks like a SteamCMD issue. Try removing the container and re-creating it?

**Comment by shaguarger** [comment] 2021-07-28 21:14
So I tried to remove everything without success. :|

```
rm -rf config/steam/* config/gamefiles/*
docker container prune
docker image prune --all
```

It printed out stuff, but nothing important:

```
satisfactory-server    | Work thread 'CHTTPClientThreadPool:1' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | Work thread 'CHTTPClientThreadPool:0' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | Work thread 'CHTTPClientThreadPool:2' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
satisfactory-server    | Work thread 'CHTTPClientThreadPool:1' is marked esatisfactory-server exited with code 137
```

I checked `docker stats` for mem usage, but it won't use more then 20MB.

**Comment by wolveix** [comment] 2021-07-29 09:37
You don't need to purge the image, you just need to stop and remove the current container. All mapped contents can stay as they are, too. Since you're using Docket Compose, the following should suffice:

```bash
docker-compose down
docker-compose up -d
docker logs satisfactory-server -f
```

**Comment by shaguarger** [comment] 2021-07-29 12:21
I know. It was pure desperation. I tried a lot of up/down.

**Comment by wolveix** [comment] 2021-07-29 12:23
Ah, okay. Could you provide the container's logs after the new container starts, please?

**Comment by shaguarger** [comment] 2021-07-29 19:04
```
user@server:/opt/satisfactory# docker-compose down
Removing network satisfactory_default
WARNING: Network satisfactory_default not found.



user@server:/opt/satisfactory# docker-compose up -d
Creating network "satisfactory_default" with the default driver
Creating satisfactory-server ... done



user@server:/opt/satisfactory# docker logs satisfactory-server -f
Checking available space...
Downloading the latest version of the game...
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK
@sSteamCmdForcePlatformType windows
"@sSteamCmdForcePlatformType" = "windows"
Logging in user 'steam_account' to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
force_install_dir /config/gamefiles
app_update "526870"
Success! App '526870' already up to date.
quit
/root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
```

**Comment by shaguarger** [comment] 2021-07-29 19:08
So I added the Steam directories as volumes in the docker-compose.yml

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        volumes:
            - ./config:/config
            - ./steam:/root/.steam
            - ./logs:/root/Steam/logs
        restart: unless-stopped
```

Noting to find in the Steam logs.

**Comment by wolveix** [comment] 2021-07-30 16:43
Yeah it's not related to any recent changes; this is a SteamCMD issue which I'm currently investigating. I'm unable to replicate the issue on my end (fresh install).

**Comment by wolveix** [comment] 2021-07-30 17:14
I wonder if this is permissions-related, similarly to the issue experienced in #11. Could you try running the container without any bound directories?

**Comment by shaguarger** [comment] 2021-07-30 17:55
Without any volumes, still no:

```
satisfactory-server    |  Update state (0x81) verifying update, progress: 94.46 (15930835827 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 95.51 (16108794509 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 96.58 (16289363193 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 97.63 (16466097269 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 98.67 (16640874479 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 99.71 (16816173408 / 16865339122)
satisfactory-server    | Success! App '526870' fully installed.
satisfactory-server    | quit
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
```

**Comment by wolveix** [comment] 2021-07-30 18:01
So just to confirm, you had no directory bindings either?

**Comment by shaguarger** [comment] 2021-07-30 18:24
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        build: ./satisfactory-server
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        restart: unless-stopped
```

`docker-compose up` ran as root

I also tried another run with your latest just to be sure:

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        restart: unless-stopped
```

No success either:

```
satisfactory-server    |  Update state (0x81) verifying update, progress: 97.76 (16487647626 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 98.84 (16668956202 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 99.92 (16851474362 / 16865339122)
satisfactory-server    | Work thread 'CContentUpdateContext::m_pCPUTh' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | Success! App '526870' fully installed.
satisfactory-server    | quit
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
satisfactory-server exited with code 137
```

**Comment by wolveix** [comment] 2021-07-30 18:32
Hmm, now that is a strange one. What OS & arch is your host running? For example, Debian 64-bit amd64

**Comment by shaguarger** [comment] 2021-07-30 20:01
```
uname -a
Linux xxxx 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wolveix** [comment] 2021-07-30 20:05
Could you try the following:

```
cd /path/to/your/mapped/config
rm -rf steam
docker-compose down
docker-compose up -d
docker logs satisfactory-server -f
```

**Comment by VergilzG** [comment] 2021-07-31 21:01
Hello, thanks for your work @wolveix . I'm also experincing an issue with the latest update. I was using the previous update of the docker image, it was fine. This new update doesn't start the server. 

I'm using docker through Synology (218+), when starting it immediately stopped without any logs.
I updated 2 days ago. I had all content ready to start with the previous working update. I tried to delete all the docker (image & files) and still not running.

Now it's more critical that yesterday, it's freezing my NAS, I've to force shutdown to make it responding (Don't know why but it's happening only on your image, I'm not blaming you).

I don't have any knowledge on Docker. I'm just a user and sending you a feedback.

**Comment by wolveix** [comment] 2021-07-31 21:52
Appreciate the kind words @VergilzG. Unfortunately, while I appreciate where you're both coming from, nothing has drastically changed with the latest 2 commits, and certainly nothing that should impact the running of the container. This issue is particularly hard to diagnose as I'm unable to reproduce it myself. The only change that _could_ have impacted the image was where the auto build was failing due to an issue with one of the upstream images (this repo is based on `steamcmd/steamcmd`, which is based on `ubuntu`). I've just made a change which _might_ help the issue, but this is pure speculation. I'm sorry that you're both experiencing difficulties, but I appreciate your feedback and assistance in resolving the issue :) 

Please pull the latest version of the image and let me know whether it resolves the issue or not.

**Comment by VergilzG** [comment] 2021-07-31 23:09
Thanks for the fast update, I pulled the latest update, unfortunately from my side it's not working but it's better. It doesn't freeze the entire NAS this time, it's launching the container, however, it's not downloading the game and crashed after couple of minutes later. I tried to rerun after that, it immediately stop with the following errors

```
Satisfactory
date,stream,content
2021-07-31 22:11:54,stdout,/root/.steam/steamcmd/steamcmd.sh: line 38:    16 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"
2021-07-31 22:11:54,stdout,
2021-07-31 22:11:54,stdout,/tmp/dumps/crash_20210731220221_1.dmp
2021-07-31 22:11:54,stdout,crash_20210731220221_1.dmp[28]: Uploading dump (out-of-process)
2021-07-31 22:11:54,stdout,
2021-07-31 22:11:54,stdout,/tmp/dumps/assert_20210731221154_8.dmp
2021-07-31 22:11:54,stdout,assert_20210731221154_8.dmp[25]: Uploading dump (out-of-process)
2021-07-31 22:11:54,stdout,Thread failed to initialize
2021-07-31 22:11:54,stdout,src/tier0/threadtools.cpp (4044) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
2021-07-31 22:11:53,stdout,[----] Extracting package...
2021-07-31 22:11:53,stdout,[----] Download complete.
2021-07-31 22:02:35,stdout,[  0%] Checking for available updates...
2021-07-31 22:02:35,stdout,[  0%] Downloading update...
2021-07-31 22:02:35,stdout,[----] Verifying installation...
2021-07-31 22:02:21,stdout,[  0%] Checking for available updates...
2021-07-31 22:02:21,stdout,Redirecting stderr to '/root/.steam/logs/stderr.txt'
2021-07-31 22:02:21,stdout,Downloading the latest version of the game...
2021-07-31 22:02:21,stdout,Checking available space...
```

![image](https://user-images.githubusercontent.com/86849262/127754326-49051498-8edc-40fe-89e6-70b1204b9b71.png)

(Docker time is not up to date, 23:00 (11PM) on the screen is currently 01:00 AM)

How it's managed on synology : https://www.youtube.com/watch?v=krHZB3D_U9E

**Comment by wolveix** [comment] 2021-07-31 23:30
Really appreciate the video as well as your help! Very interesting. So, the `.cpp`-related issues seem to be due to a permissions issue on the host, but it could just be a side-effect of something else. Just a quick note, if you intend to run the server on a non-default port, make sure to keep the container's internal port as 7777 and just change the exposed port to 7778, not both. 

Those crash logs could be useful, but I want to test something else first. Could you try pulling `wolveix/satisfactory-server:dev` and see whether that makes any difference? Thanks!

**Comment by VergilzG** [comment] 2021-08-01 13:34
Hi @wolveix, I downloaded the dev container.
It looks same issue as above. (It was freezing my NAS, I think the CPU may be to low for the containers)

![image](https://user-images.githubusercontent.com/86849262/127772649-eb3a0301-bc02-4447-99ec-dcc0874a2e2d.png)

This time I kept port 7777.

I also forgot to mention that the PROD container wolveix/satisfactory-server:latest is creating folders.

![image](https://user-images.githubusercontent.com/86849262/127772759-289feb28-9c80-4ea0-bd7e-63cf5ea1a678.png)

For the logs I will check it, I'm not familiar with SSH, or I will have to find the folder to mount it.

**Comment by wolveix** [comment] 2021-08-01 17:52
So the `dev` image tag is the same code from 2 months ago (prior to the new commits). The only things that could be causing this is a change in your local environment (which I'm leaning less likely to) or a change upstream, as the `dev` image was still built with the latest upstream images. Those crash logs would be really useful to see.

I'm going to see if I have an older version of the image cached somewhere, then hopefully you can test it to rule stuff out.

**Comment by wolveix** [comment] 2021-08-01 17:58
@VergilzG I found an older build from 3 months ago, which I've just pushed to `wolveix/satisfactory-server:dev`. Please test this and report back :)

**Comment by shaguarger** [comment] 2021-08-01 19:45
With your build from 3 month ago it is working again! 🥳

**Comment by wolveix** [comment] 2021-08-01 20:11
Seems that there's an issue with one of the upstream images then! Damn, that's frustrating. Really appreciate your feedback with this issue :) Glad that it's working again for you! But now I need to figure out the underlying issue with one of the upstream images. I'll try some stuff and kindly request your assistance with the new version once it's ready! Purely as I'm unable to recreate the issue myself, so I have no way of knowing whether it's resolved or not without your help.

**Comment by VergilzG** [comment] 2021-08-01 20:18
Yeah, I confirm that, it's working with the old image (DEV).

I will be glad to help you to solve it.

**Comment by wolveix** [comment] 2021-08-01 21:05
Looks like our upstream image `steamcmd/steamcmd:latest` changed their OS from Ubuntu 18 to Ubuntu 20, which is the only thing I can see that may have had an impact in edge cases. I've pushed the latest version of this repo to the `dev` tag, using the `steamcmd/steamcmd:ubuntu-18` image upstream. Please test this either @shaguarger or @VergilzG and let me know whether it still works! Thanks in advance!

**Comment by shaguarger** [comment] 2021-08-01 22:10
back to broken with the latest dev.

```
Attaching to satisfactory-server
satisfactory-server    | Checking available space...
satisfactory-server    | Downloading the latest version of the game...
satisfactory-server    | Redirecting stderr to '/root/Steam/logs/stderr.txt'
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | [----] Verifying installation...
satisfactory-server    | Steam Console Client (c) Valve Corporation
satisfactory-server    | -- type 'quit' to exit --
satisfactory-server    | Loading Steam API...OK
satisfactory-server    | @sSteamCmdForcePlatformType windows
satisfactory-server    | "@sSteamCmdForcePlatformType" = "windows"
satisfactory-server    | Logging in user 'xxxxxxx' to Steam Public...OK
satisfactory-server    | Waiting for client config...OK
satisfactory-server    | Waiting for user info...OK
satisfactory-server    | force_install_dir /config/gamefiles
satisfactory-server    | app_update "526870"
satisfactory-server    | Success! App '526870' already up to date.
satisfactory-server    | quit
satisfactory-server    | cp: cannot stat '/root/.steam/config/config.vdf': No such file or directory
satisfactory-server    | satisfactory-server exited with code 1
```

**Comment by wolveix** [comment] 2021-08-01 22:30
That's a totally different issue. I've just pushed a fix for it, please try pulling the image again :)

**Comment by VergilzG** [comment] 2021-08-02 04:12
> That's a totally different issue. I've just pushed a fix for it, please try pulling the image again :)

The latest DEV image is working, on empty map and vanilla it's working
![image](https://user-images.githubusercontent.com/86849262/127803319-c8ba14ea-09e7-4e3d-a61a-60696a3c95e7.png)

On modded map it's another story (Have to troubleshoot myself if it's the map or mods causing issues).

**Comment by shaguarger** [comment] 2021-08-02 07:43
Use my coffee break to check. It works with your fix. 👍

**Closed** 2021-08-02 20:04 UTC
Labels: bug

**Comment by wolveix** [comment] 2021-08-02 20:05
> 
> 
> > That's a totally different issue. I've just pushed a fix for it, please try pulling the image again :)
> 
> The latest DEV image is working, on empty map and vanilla it's working
> ![image](https://user-images.githubusercontent.com/86849262/127803319-c8ba14ea-09e7-4e3d-a61a-60696a3c95e7.png)
> 
> On modded map it's another story (Have to troubleshoot myself if it's the map or mods causing issues).
> 
> Edit : After testing, it was just my mods (Really Simple Sign - RSS) causing issue. My orignal map is also working.
> I also tried to change the map (rename savefile.sav to .old) after shutdown the container, it's keeping to start the last map. I never tested that on the "Latest" image. To solve this I have to recreate the container. For me it's not an issue as I can save container settings and reimport.

This is due to the container always pulling the latest save file (based on modification time) to use, rather than using the name.

Thanks for your help @shaguarger and @VergilzG! Pushed the change in the latest commit :)
