### ISSUE TITLE
Steamcmd Segmentation Fault on Subsequent Container Runs

### ISSUE THREAD

**Issue by konstander** [wolveix/satisfactory-server#193] opened 2023-06-26 22:05 UTC
**Describe the Bug**
I have been experiencing container error when starting/restarting. The process is cyclical. Restarting the container or creating a new one from the image does not help. 
I run the image on the synology NAS.

A fragment of the log from the console:

```
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.15 (10493888 / 7124928656)
 Update state (0x5) verifying install, progress: 11.45 (815645455 / 7124928656)
 Update state (0x5) verifying install, progress: 23.10 (1646075198 / 7124928656)
 Update state (0x5) verifying install, progress: 34.57 (2463010896 / 7124928656)
 Update state (0x5) verifying install, progress: 46.11 (3285635716 / 7124928656)
 Update state (0x5) verifying install, progress: 57.92 (4126688358 / 7124928656)
 Update state (0x5) verifying install, progress: 69.68 (4964844867 / 7124928656)
 Update state (0x5) verifying install, progress: 81.42 (5801249014 / 7124928656)
 Update state (0x5) verifying install, progress: 93.14 (6636469831 / 7124928656)
Success! App '1690800' fully installed.
/home/steam/.steam/steamcmd/steamcmd.sh: line 39:    50 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"
Checking available memory...27GB detected
Setting autosave number to 9
Setting crash reporting to True
Setting max objects number to 2162688
Setting max tick rate to 30
Setting timeout number to 30
Setting max players to 4
Setting autosave interval to 600s
Setting disable seasonal events to 0
Setting network quality number to 3
Setting auto pause to True
Setting autosave on disconnect to True
Checking available storage...8506GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1687387651
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
OK


Connecting anonymously to Steam Public...OK
...
...
```

**Your Runtime Command or Docker Compose File**
```

{
   "CapAdd" : [],
   "CapDrop" : [],
   "cmd" : "",
   "cpu_priority" : 90,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enable_service_portal" : null,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "USER",
         "value" : "root"
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "LANGUAGE",
         "value" : "en_US:en"
      },
      {
         "key" : "AUTOPAUSE",
         "value" : "true"
      },
      {
         "key" : "AUTOSAVEINTERVAL",
         "value" : "600"
      },
      {
         "key" : "AUTOSAVENUM",
         "value" : "5"
      },
      {
         "key" : "AUTOSAVEONDISCONNECT",
         "value" : "true"
      },
      {
         "key" : "CRASHREPORT",
         "value" : "true"
      },
      {
         "key" : "DEBUG",
         "value" : "false"
      },
      {
         "key" : "DISABLESEASONALEVENTS",
         "value" : "false"
      },
      {
         "key" : "GAMECONFIGDIR",
         "value" : "/config/gamefiles/FactoryGame/Saved"
      },
      {
         "key" : "GAMESAVESDIR",
         "value" : "/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
      },
      {
         "key" : "MAXOBJECTS",
         "value" : "2162688"
      },
      {
         "key" : "MAXPLAYERS",
         "value" : "4"
      },
      {
         "key" : "MAXTICKRATE",
         "value" : "30"
      },
      {
         "key" : "NETWORKQUALITY",
         "value" : "3"
      },
      {
         "key" : "PGID",
         "value" : "1000"
      },
      {
         "key" : "PUID",
         "value" : "1000"
      },
      {
         "key" : "SERVERBEACONPORT",
         "value" : "15000"
      },
      {
         "key" : "SERVERGAMEPORT",
         "value" : "7777"
      },
      {
         "key" : "SERVERIP",
         "value" : "0.0.0.0"
      },
      {
         "key" : "SERVERQUERYPORT",
         "value" : "15777"
      },
      {
         "key" : "SKIPUPDATE",
         "value" : "false"
      },
      {
         "key" : "STEAMAPPID",
         "value" : "1690800"
      },
      {
         "key" : "STEAMBETA",
         "value" : "false"
      },
      {
         "key" : "TIMEOUT",
         "value" : "30"
      }
   ],
   "exporting" : false,
   "id" : "90d43a03b0c4a643eeee825838cb6b9dfeda683d8e73ef1ba30786d0b89b1735",
   "image" : "wolveix/satisfactory-server:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 17179869184,
   "name" : "wolveix-satisfactory-152",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "satisfactory"
      }
   ],
   "network_mode" : "satisfactory",
   "port_bindings" : [
      {
         "container_port" : 15000,
         "host_port" : 0,
         "type" : "udp"
      },
      {
         "container_port" : 15777,
         "host_port" : 0,
         "type" : "udp"
      },
      {
         "container_port" : 7777,
         "host_port" : 0,
         "type" : "udp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/satisfactory",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}

```

**System Specs:**
```
===== START ISSUE REPORT =====
OS:  Linux DS923plus 4.4.180+ #42962 SMP Fri May 26 23:30:43 CST 2023 x86_64 GNU/Linux synology_r1000_923+
CPU:
RAM: 27GB/32GB
HDD sys: 1GB/2GB (79% used)
HDD total: 11T/2.2T (21% used)
===== END ISSUE REPORT =====
```

**Additional Context**

```
docker images | grep satisfactory
wolveix/satisfactory-server   latest    e2494126d956   9 days ago    413MB
```

**Comment by wolveix** [comment] 2023-06-26 22:46
Ah, Synology. Thanks for opening this @konstander. Is that RAM calculation without the server running? If so, that's not enough RAM to run the server.

This looks to be the same error as experienced here: https://github.com/parkervcp/eggs/issues/2302

It's not an issue with the image, but with steamCMD. I can't properly look into it right this second, but I can take a proper look tomorrow

**Comment by konstander** [comment] 2023-06-26 23:17
> Ah, Synology. Thanks for opening this @konstander. Is that RAM calculation without the server running? If so, that's not enough RAM to run the server.
> 
> This looks to be the same error as experienced here: [parkervcp/eggs#2302](https://github.com/parkervcp/eggs/issues/2302)
> 
> It's not an issue with the image, but with steamCMD. I can't properly look into it right this second, but I can take a proper look tomorrow

27Gb of free RAM out of 32Gb. The container is limited in settings to 16GB.
The catch is precisely in the error, there is a mention in line 39 in the startup script steamcmd.sh I can't see its contents.

**Comment by konstander** [comment] 2023-06-27 07:38
> The SDL team is focusing on SDL 3.0 and all new feature development will be happening there.
> 
https://github.com/libsdl-org/SDL/releases
Only 2.x version now. :(

**Comment by konstander** [comment] 2023-06-27 07:42
Hey, @wolveix 
Perhaps this can help in correcting the image?
https://github.com/libsdl-org/SDL/issues/7841

**Comment by wolveix** [comment] 2023-06-27 11:29
@konstander I've just verified that this is happening for me to, due to the SteamCMD update you referenced. However, it doesn't stop the container at all for me. Is it causing your container to not properly startup?

**Comment by konstander** [comment] 2023-06-27 22:09
@wolveix Based on the text in the log, there is a file integrity check, then the libSDL 3 error and the game server does not start as usual. The container stops.

**Comment by wolveix** [comment] 2023-06-27 22:14
@konstander hm, that's weird. Maybe mine still starts since I already have the game files downloaded

**Comment by wolveix** [comment] 2023-06-27 22:46
@konstander I tried with a clean directory, and it still continued. I'm not sure why your container is terminating prematurely. I'll test a fix with the SDL files present, but that may not be the issue.

Oh wait, I've just spotted the segmentation fault error in your log. That'll be the real issue.

**Comment by wolveix** [comment] 2023-06-27 22:49
@konstander I don't personally have experience with Synology's interface, but it's been the cause of a lot of issues since the inception of this repo.

The spec you gave in place of a normal Docker run or Docker Compose file is interesting, that's what Synology gives you, right? What did you specify when initially running the container?

**Comment by konstander** [comment] 2023-06-28 14:03
@wolveix 

> Oh wait, I've just spotted the segmentation fault error in your log. That'll be the real issue.

Perhaps. All I understood was that the files are checked 100%, similarly, the files are downloaded 100% (if you delete everything). But then the server does not start. Perhaps some error during verification or transmission of an "error signal" to the log stops the process. I don't understand well at this moment.

It usually ends there:
```home/steam/.steam/steamcmd/steamcmd.sh: line 39:    50 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"```

> The spec you gave in place of a normal Docker run or Docker Compose file is interesting, that's what Synology gives you, right? What did you specify when initially running the container?

I am using the docker application (package) in synology nas.
The settings file I have given is the container configuration export file. Unfortunately, input options via the "console" (as on a PC) via the DSM synology interface (GUI) are not supported, I did not try using SSH.
I repeat, earlier everything worked with your image. All container parameters are perfectly configured in the graphical shell of the docker application.

![image](https://github.com/wolveix/satisfactory-server/assets/81830320/5c7446a5-bc12-487c-b189-c7d9670704c2)

**Comment by konstander** [comment] 2023-06-28 15:42
An interesting observation:
1) I delete the file in the config folder..\gamefiles\Factory Server.sh
The container starts properly!
2) In the game, I make the primary server settings - the administrator's name, password, etc. I try to load the save - the container crashes.

**Comment by konstander** [comment] 2023-06-28 16:46
update.
In the container settings, I set the value SKIP UPDATE = true
Starting, stopping, restarting the container goes fine.
Very interesting...

**Comment by wolveix** [comment] 2023-06-28 17:48
Yeah, setting `SKIPUPDATE=true` will completely ignore SteamCMD, hence why it works :D I still don't really understand why your specific environment isn't handling SteamCMD properly, and crashing. I did update the image manually last night, but I merely rebuilt it in the hopes that an upstream update may resolve the issue for you

**Comment by konstander** [comment] 2023-06-28 18:06
**Thank you.** While they will use this temporary solution. I hope when you have more time you will pay attention to this problem more closely.

**Comment by m3talliz3d** [comment] 2023-06-29 15:19
> @wolveix **Some more of my research in the process of layout errors.** In the container settings, I set the value SKIP UPDATE = true Starting, stopping, restarting the container goes fine. Very interesting...
> 
> If I understood everything correctly, SteamCMD incorrectly transmits information about the results of file verification to the log, something "listens", does not receive the desired response... Somewhere I read about a similar error, I find it difficult to remember where exactly.

@konstander 
I had the same issue and when I stopped set `SKIPUPDATE = true` it worked fine.

I will try to investigate this behavior...

@wolveix  If I want to debug should I use the docker DEBUG command or or use the DEBUG value mentioned in the EnviromentalVariable?

**Comment by wolveix** [comment] 2023-06-29 15:51
@m3talliz3d use Docker's debug, since the DEBUG environment just prints some additional information for troubleshooting issues. It's not particularly applicable in this use-case. Are you also using Synology?

**Comment by m3talliz3d** [comment] 2023-06-29 19:13
@wolveix I am using satisfactory Experimental as Docker container on Ubuntu VM that is hosted on ESXi, also I got another one on Proxmox CT but not using it as it has less resources.

**Comment by wolveix** [comment] 2023-06-29 19:29
@m3talliz3d and you're experiencing the same issue with the game server not launching?

**Comment by m3talliz3d** [comment] 2023-06-29 20:06
@wolveix well, when I choose update to be true, it show an error with network when trying to connect and fail to connect to game.

Yet, I need to confirm further and perform another test, since I already decreased the resource limits (reserve 6GB and limit to 16GB [My VM was 18GB) it was failing, and when I reverted back to set update=false and increased VM Ram to 24 and limits to the one you provided (doc compose) it worked fine.

Anyway, I will test again when am back home different scenarios just to isolate the culprit of the issue and will report back.

I would like to thank you for your efforts in dockerizing the game server. Fantastic work.

**Comment by silen72** [comment] 2023-06-30 12:25
I had the same or at least a very similar issue today after switching to experimental. On startup it did a suspicously small download (like 90MB), then complained about libSDL3.so.0 and crashed with a seg fault shortly after. In between it said "no executable found". Rinse and repeat. After switching back to early access, it downloaded a considerably larger package, installed it and the server is back to functional. Not compatible with my satisfactory client but functional. So experimental = broken, EA = working - at least for me. Not on synology but on a home made server running ubuntu server 22.04.02.

**Comment by wolveix** [comment] 2023-06-30 12:28
@silen72 thank you very much, that's great to know. I'll do some testing on my end to reproduce the issue, then I can work on resolving it :)

**Comment by wolveix** [comment] 2023-06-30 12:30
@silen72 ah, no, no executable found is most likely due to you running an older image. Please make sure you're running the latest image, as Update 8 required a slight change to the image to pickup the new server executable location. Your image hash should look like this:

```
❯ docker images | grep satisfactory
wolveix/satisfactory-server                 latest              f13f51f7abdf   2 days ago      417MB
```

**Comment by wolveix** [comment] 2023-06-30 12:32
@konstander I just realised that this whole issue is a duplicate of #188. In that, @Reticulmz resolved their issue by reinstalling Docker. Of course I'd love to gain a greater insight into what may be causing this issue, but I do suspect that it's not an issue with the image itself

**Comment by Reticulmz** [comment] 2023-06-30 12:40
In my case, I think it's because wsl2 didn't free memory and steamcmd didn't start due to lack of memory.
I think you can avoid the error by specifying the memory limit or swap in .wslconfig for example.

**Comment by wolveix** [comment] 2023-06-30 12:44
@Reticulmz ah, I really appreciate that insight :)

**Comment by Reticulmz** [comment] 2023-06-30 12:45
I've been doing some digging around, and maybe it's due to running out of stack space.
Try checking with ulimit -a.

**Comment by m3talliz3d** [comment] 2023-06-30 13:19
That is strange... everything is working fine now.


>===== START ISSUE REPORT =====
> Hardware: ESXi 6.7U3
> OS:  Linux satisfactoryd 5.4.0-153-generic #170-Ubuntu (Ubuntu 20.04.1 LTS) SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> RAM: 10GB/11GB 
> HDD: 19GB/98GB (20% used)
> ===== END ISSUE REPORT =====

_**Note: RAM = 23GB/24GB**_

**T#1:** (update=false)
-> Ran `docker compose up`  .
-> connected to the game and it worked.

**T#2:**
-> Stopped container with `docker compose down` .
-> reverted update to true as default" .
-> Started container.
-> Connected to game successfully.

**T#3:**
-> Stopped container with `docker compose down` .
-> Set limits to
--> Limit = 10 GB
--> Reservation = 8GB
-> Started container.
-> Connected to game successfully.

**T#4:**
-> Stopped container with `docker compose down` .
-> Power off VM and change its RAM to 12GB instead of 24GB
-> Started container. (with same docker-compose changes in T#3)
-> Connected to game successfully.


I am not sure what was the issue exactly before but the error I had previously was
```bash
[2023.06.29-08.52.31:353][980]LogNet: NetworkFailure: ConnectionTimeout, Error: 'UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 30.00, Real: 30.00, Good: 30.00, DriverTime: 68083.64, Threshold: 30.00, [UNetConnection] RemoteAddr: 172.18.0.1:60447, Name: IpConnection_2147481141, Driver: GameNetDriver NetDriverEOSBase_2147481943, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: EOS:(EOS)3f9f7a418b434065adb3853ff12de642|000289f1418a4c7dbf726ddc36c37f89'
```

now it looks like everything is running smoothly.

@Reticulmz What is your RAM available to be used or the one that WSL use/allocate?

**Comment by silen72** [comment] 2023-06-30 15:28
@wolveix Thanks for the hint, that did the trick for me.

**Comment by konstander** [comment] 2023-07-01 16:58
> @konstander I just realised that this whole issue is a duplicate of #188. In that, @Reticulmz resolved their issue by reinstalling Docker. Of course I'd love to gain a greater insight into what may be causing this issue, but I do suspect that it's not an issue with the image itself

Sounds like critical luck. ^^ The solution is more suitable for a PC.
Of course I'm trying to reinstall the docker package on my synology NAS. I'll tell you what happened. Most likely, the problem is really not in the image itself, but in steamcmd.

**Comment by konstander** [comment] 2023-07-01 18:55
Checked reinstalled docker. At the same time, I installed the new DSM update `DSM 7.2-64570 Update 1` recently, a new version has arrived.
With the `SKIP UPDATE = true`  the server starts.
With the `SKIP UPDATE = false` restarting the container results in a fragmentation error as usual: 
`home/steam/.steam/steamcmd/steamcmd.sh: line 39:    50 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"`
Ideas are over for now.

**Comment by m3talliz3d** [comment] 2023-07-01 18:57
@konstander are you able to get the core dump file name?

**Comment by konstander** [comment] 2023-07-01 18:59
@m3talliz3d 
> @konstander are you able to get the core dump file name?
> 
> It should be in /core as far as I recall, and if that is the case, do a mount for /core to persistent in case it is huge dump.

What do you mean, describe in more detail?

**Comment by m3talliz3d** [comment] 2023-07-01 19:10
As far as I recall, segmentation fault could be caused because process ran out of memory, thus it created a core dump, core dump in Linux is a way where...... when a process fail, it dumps its memory data ito a file so it can inspected later with specific tool.

Core dump is usually saved in location '/core', in case this is the scenario then you could mount './core:/core' to have it persistent.

I am not sure what is the issue, but as Ex-VMware support we used to have our core dumps in /core directory.

Got lost? @konstander

**Comment by konstander** [comment] 2023-07-01 19:15
@m3talliz3d  It's clear, but I don't know in which directory the dump is saved in this particular image. Maybe it will tell me @wolveix

**Comment by m3talliz3d** [comment] 2023-07-01 19:21
@konstander when it show this error. Does the container stop? If not can you exec into container and perform 'df -h' and check if you can notice which partition/directory got almost full.

I will check the file structure when I get home.

**Comment by konstander** [comment] 2023-07-01 19:45
@m3talliz3d 
`df -h`
```
# docker exec -ti satisfactory-server sh
# df -h
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/cachedev_1   11T  2.3T  8.2T  22% /
tmpfs                    64M     0   64M   0% /dev
tmpfs                    16G     0   16G   0% /sys/fs/cgroup
shm                      64M     0   64M   0% /dev/shm
/dev/mapper/cachedev_1   11T  2.3T  8.2T  22% /core
/dev/mapper/cachedev_1   11T  2.3T  8.2T  22% /etc/hosts
tmpfs                    16G     0   16G   0% /proc/acpi
tmpfs                    16G     0   16G   0% /proc/scsi
tmpfs                    16G     0   16G   0% /sys/firmware
```

**Comment by m3talliz3d** [comment] 2023-07-01 20:15
ls /core

![image](https://github.com/wolveix/satisfactory-server/assets/39600112/68acd051-66d5-49b8-8284-2e289a18271b)

**Comment by konstander** [comment] 2023-07-01 20:25
nothing

**Comment by konstander** [comment] 2023-07-06 17:11
For the sake of interest, I tried to launch an image of another author, check what will happen. You know what? Starts, stops restarts and no fragmentation errors. ><

**Comment by m3talliz3d** [comment] 2023-07-06 18:28
> For the sake of interest, I tried to launch an image of another author, check what will happen. You know what? Starts, stops restarts and no fragmentation errors. ><
> 
> p.s.
> 
> By the way, thanks to the update of the DSM interface in synology, the docker package has acquired the function of "launching projects", including through the Docker Compose file. It is a pity that this did not solve the fragmentation problem.

That is such a fantastic news, I hope you will still consider trying with wolveix image until a resolution is found.

I am actually very interested to get that issue fixed and if applicable I don't mind having a session with you, me and @wolveix to troubleshoot live.

Thanks for your update!

**Comment by wolveix** [comment] 2023-07-06 18:46
@konstander would you mind sharing what image ended up working for you? :)

**Comment by konstander** [comment] 2023-07-07 09:20
> @konstander would you mind sharing what image ended up working for you? :)
@wolveix Sure, [url](https://hub.docker.com/r/donimax/satisfactory-docker) The author has problems with access rights "out of the box", but it doesn't matter.

**Comment by wolveix** [comment] 2023-07-07 09:47
@konstander huh, that's interesting. Looks like they forked my repo to begin with (everything is laid out identically to an old commit), but they mever adopted our perms fixes for people.

That could potentially be where the issue lies? I'll have a proper look through in a bit, but that's really interesting 😅

**Comment by wolveix** [comment] 2023-07-07 15:10
It's hard to remember everything that we've tried during this troubleshooting :P Have you tried running without a bind mount? So removing the `volumes:` declaration in your Docker Compose

**Comment by konstander** [comment] 2023-07-07 22:37
No. I will try.

**Comment by comzyh** [comment] 2023-07-08 11:56
Same issue after I upgraded from last year's version eee7de98370e to f13f51f7abdf without cleanup.
I will try to debug.

**Comment by comzyh** [comment] 2023-07-08 12:43
My problem just disappears. 

For who want to debug, can just try to use docker-compose run to avoid the container to be destroyed after the server fail.
```
docker-compose run --entrypoint /bin/bash --service-ports -- satisfactory-server
```
then manually use `/init.sh` to start the server.

I use `/init.sh` to start the server and the first try failed as described in this issue and the second run is just a success.

Also I can confirm that the issue is not related to lib libSDL3.so

> libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory

I got this libSDL3 line output still, but my server is already working.

**Comment by wolveix** [comment] 2023-07-10 13:28
@konstander any update? :)

**Comment by konstander** [comment] 2023-07-13 16:56
I'm sorry, I'm sick. I'll resume testing as soon as I feel better.

**Comment by konstander** [comment] 2023-07-13 17:20
Still, I did a short test. I used the standard Docker Compose file recommended by you. Created a container without mounting the "config" folder.  Removed the line:
`volumes:
            - '/path/to/config:/config'`
With the `SKIP UPDATE = false`
Restarting the container, I get a fragmentation error.
`home/steam/.steam/steamcmd/steamcmd.sh: line 39:    50 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"`

**Comment by wolveix** [comment] 2023-07-13 18:07
@konstander sorry to hear you're ill, I hope you feel better soon! You mentioned you _restarted_ the container. Does this mean that you didn't do `docker compose up -d` after making this change? Simply restarting the container won't pick up the config changes.

**Comment by konstander** [comment] 2023-07-16 17:51
Earlier I did not quite put it correctly: not only restarting, but also stopping and restarting again. Without a difference.
I created a new project from scratch using the settings, not the rules of an existing project.

**Comment by wolveix** [comment] 2023-07-16 18:12
@konstander if you fully rebuilt the container, then I'm not sure what else to suggest. It's not a permissions issue at that point, there's something else going on

**Comment by wolveix** [comment] 2023-07-16 20:39
@konstander could you remove the memory restrictions in your Docker Compose file? At this point I'm about ready to order the same Synology to test this myself 😂

**Comment by konstander** [comment] 2023-07-16 21:18
@wolveix And... same ^^

**Comment by konstander** [comment] 2023-07-16 21:29
https://developer.valvesoftware.com/wiki/SteamCMD#Known_Issues
ulimit?

**Comment by erikjunker** [comment] 2023-07-19 19:37
Hi guys. Just wanted to chime in as I am also getting the segmentation fault on my Synology NAS. I tried to delete the docker container and start it again with the following command:

`docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1033 -e STEAMBETA=true -v /volume1/docker/satisfactory-server:/config -m 16G --memory-reservation=12G -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest`

And it worked! Until I tried to shut down the server and start it up again. The segmentation fault struck again.
I tried using the ulimit command konstander referenced above, that did not seem to change anything (although perhaps I misunderstood how that was supposed to work)

SKIPUPDATE = true allows the server to start so guess I'll just use that until a fix is found. I assume I can just remove the container and re-create it with the above command should a steamcmd update arrive in the meantime.

If there's any testing I can contribute to, then I'm happy to help

**Comment by rnarma321** [comment] 2023-07-21 15:02
@wolveix hey I do docker stuff at work and just saw this thread when I was trying to run this locally. I had it running once when I didn't mount the save files locally, but once I moved over to mounting the volume to a local file I was no longer able to even start the system for the first time. I am going to play around a little more and see if I can get consistent results and try to help out a little

**Comment by wolveix** [comment] 2023-07-21 15:38
@rnarma321 sounds like there's a configuration issue in how you're binding the mount :) Feel free to open a discussion request if you're unsure/need help. I work with Docker daily at work :D

The issue with this overarching GitHub issue is that I can't personally reproduce it, no matter what I do. Until I can, fixing it is a little cumbersome. @erikjunker it's great to find someone else that is experiencing the same issue! Well, not great for you of course, but hopefully it'll cut down on the time needed to investigate the issue. Please try some of the steps I mentioned above, particularly try launching the container **without** any bind mount. This should work without any issues

**Comment by rnarma321** [comment] 2023-07-21 19:29
I was having the same issue you guys were having last night `satisfactory-server  | /home/steam/.steam/steamcmd/steamcmd.sh: line 39:    80 Segmentation fault      $DEBUGGER "$STEAMEXE" "$@"`, but when I restarted my computer and ran the system including binding the mount, it seemed to work. I am not sure if it broke because I had it not binded to a local directory, and then switching it into a local directory between builds without restarting my PC

**Comment by wolveix** [comment] 2023-07-21 19:32
@rnarma321 it wasn't clear that you'd experienced the error from your previous reply. Could you clarify how you resolved the issue?

**Comment by rnarma321** [comment] 2023-07-21 20:26
I just restarted my computer and have been able to close and open the server without issues, I just can't rebuild the image without causing issues

**Comment by erikjunker** [comment] 2023-07-22 18:47
> @rnarma321 sounds like there's a configuration issue in how you're binding the mount :) Feel free to open a discussion request if you're unsure/need help. I work with Docker daily at work :D
> 
> The issue with this overarching GitHub issue is that I can't personally reproduce it, no matter what I do. Until I can, fixing it is a little cumbersome. @erikjunker it's great to find someone else that is experiencing the same issue! Well, not great for you of course, but hopefully it'll cut down on the time needed to investigate the issue. Please try some of the steps I mentioned above, particularly try launching the container **without** any bind mount. This should work without any issues


I think I have been through all the suggestions in this thread with no success, but I did just try running the image without any bind mounts:

`docker run -d --name=satisfactory-server-test -h satisfactory-server-test -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1033 -e STEAMBETA=true -m 16G --memory-reservation=12G -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest`

This starts the server without any issues. I also cannot seem to reproduce the segmentation error after restarting the server. It passes the steam update with ease and starts the server right away.

I then started the server again, this time with a bind mount but to a completely blank folder:

`docker run -d --name=satisfactory-server-test -h satisfactory-server-test -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1033 -e STEAMBETA=true -v /volume1/docker/satisfactory-server-test:/config -m 16G --memory-reservation=12G -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest`

Again, the server starts without any issues - I can connect, play and everything works great. I then ran `docker restart satisfactory-server-test` and this throws the segmentation error:

`[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1689642531
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
/home/steam/.steam/steamcmd/steamcmd.sh: line 39:    50 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"
Waiting for user info...`

I tried this three times (each time with a clean folder), and it had a 100% reproduction rate.

**Comment by wolveix** [comment] 2023-07-22 18:55
@erikjunker really appreciate your research! Seems as I thought :) Could you check the contents of `steamcmd`'s error log?

**Comment by erikjunker** [comment] 2023-07-22 21:33
> @erikjunker really appreciate your research! Seems as I thought :) Could you check the contents of `steamcmd`'s error log?

Where do I find this log file? Google is leaving me a bit empty handed. I only have access to the log file of the docker container itself, but I don't suppose that's what you're after.
I tried digging around in some of the subvolumes for the docker containers, but I was unable to locate the log files. Hope you can provide some guidance.

**Comment by wolveix** [comment] 2023-07-26 15:49
Apologies @erikjunker, been a very busy week or so. I believe the relevant log file is `/home/steam/.steam/logs/stderr.txt`

**Comment by wolveix** [comment] 2023-08-05 21:59
@erikjunker @konstander any updates?

**Comment by wolveix** [comment] 2023-08-13 12:19
I'm gonna close this out as I'm unable to reproduce the issue myself due to it seemingly being environment-related. Happy to re-open should there be any new developments!

**Closed by wolveix** 2023-08-13 12:19 UTC
Labels: help wanted
