### ISSUE TITLE
Dedicated server don't start with error "Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again."

### ISSUE THREAD

**Issue by killpilot80** [wolveix/satisfactory-server#154] opened 2022-11-14 11:04 UTC
**Describe the Bug**
since a few weeks (release of update 6) I deleted and recreated my docker image to restart my server, and since the container refuses to start. 

In the logs I have the following error:
Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.

when I launch the container with entry-point /bin/bash that I wait a little and that I launch the startup script, it works, I have the impression that the container starts too quickly and that something is not ready.

Translated with www.DeepL.com/Translator (free version)

**Your Runtime Command or Docker Compose File**
```
docker run -d --restart=always --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -v /data/Docker_Config/satisfactory:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux ns3039776.ip-91-121-86.eu 4.9.120-xxxx-std-ipv6-64 #327490 SMP Thu Aug 16 10:11:35 UTC 2018 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
RAM: 13GB/15GB
HDD: 36GB/48GB (78% used)
===== END ISSUE REPORT =====
```

**Additional Context**
here the docker logs extract (from json log file into docker folder): 
```
{"log":"Checking available memory...13GB detected\n","stream":"stdout","time":"2022-11-14T10:50:11.242365746Z"}
{"log":"Setting max objects number to 2162688\n","stream":"stdout","time":"2022-11-14T10:50:16.709930056Z"}
{"log":"Setting timeout number to 300\n","stream":"stdout","time":"2022-11-14T10:50:16.715104688Z"}
{"log":"Setting autosave number to 5\n","stream":"stdout","time":"2022-11-14T10:50:16.720243893Z"}
{"log":"Setting crash reporting to True\n","stream":"stdout","time":"2022-11-14T10:50:16.722625709Z"}
{"log":"Setting max players to 4\n","stream":"stdout","time":"2022-11-14T10:50:16.724908878Z"}
{"log":"Setting autosave interval to 300s\n","stream":"stdout","time":"2022-11-14T10:50:16.727265543Z"}
{"log":"Setting disable seasonal events to 0\n","stream":"stdout","time":"2022-11-14T10:50:16.729612961Z"}
{"log":"Setting network quality number to 3\n","stream":"stdout","time":"2022-11-14T10:50:16.73207198Z"}
{"log":"Setting auto pause to True\n","stream":"stdout","time":"2022-11-14T10:50:16.734333535Z"}
{"log":"Setting autosave on disconnect to True\n","stream":"stdout","time":"2022-11-14T10:50:16.736441942Z"}
{"log":"Checking available space...278GB detected\n","stream":"stdout","time":"2022-11-14T10:50:16.740610545Z"}
{"log":"Downloading the latest version of the game...\n","stream":"stdout","time":"2022-11-14T10:50:16.740632541Z"}
{"log":"Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'\n","stream":"stdout","time":"2022-11-14T10:50:16.816757392Z"}
{"log":"src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.\n","stream":"stdout","time":"2022-11-14T10:50:16.84767347Z"}
{"log":"[  0%] Checking for available updates...\n","stream":"stdout","time":"2022-11-14T10:50:16.847702948Z"}
{"log":"Thread failed to initialize\n","stream":"stdout","time":"2022-11-14T10:50:16.847709559Z"}
{"log":"src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.\n","stream":"stdout","time":"2022-11-14T10:50:16.847724191Z"}
{"log":"Thread failed to initialize\n","stream":"stdout","time":"2022-11-14T10:50:16.847729748Z"}
{"log":"CWorkThreadPool::StartWorkThread: Thread creation failed.\n","stream":"stdout","time":"2022-11-14T10:50:16.849741635Z"}
{"log":"src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.\n","stream":"stdout","time":"2022-11-14T10:50:16.849803323Z"}
{"log":"Thread failed to initialize\n","stream":"stdout","time":"2022-11-14T10:50:16.849812068Z"}
{"log":"CWorkThreadPool::StartWorkThread: Thread creation failed.\n","stream":"stdout","time":"2022-11-14T10:50:16.850329915Z"}
{"log":"/home/steam/steamcmd/steamcmd.sh: line 39:    48 Segmentation fault      (core dumped) $DEBUGGER \"$STEAMEXE\" \"$@\"\n","stream":"stderr","time":"2022-11-14T10:50:16.877996834Z"}
```

**Comment by wolveix** [comment] 2022-11-17 15:11
Hey @killpilot80, thanks for taking the time to open this issue. At first I thought it was similar to #153, but this appears to be different.

I noticed that your issue report states that you only have 2GB of RAM available. I'm assuming you ran this alongside a successful deployment? If so, that rules RAM out. I'll do some tetsing on my end to see if I can reproduce this.

**Comment by killpilot80** [comment] 2022-11-18 09:04
hi wolveix,

at this moment (execute script to display information) the docker is up and running and try to start, and i suppose , consume memory, but after stop it, the memory decrease at normal value 2,3G / 16G ..

**Comment by killpilot80** [comment] 2022-11-22 09:40
hi, i try ti remplace all -p by --net=host same result for me....

**Comment by Selfmade-RuLeZ** [comment] 2022-11-22 17:14
After some reviews from other issues I see the problem: 
https://github.com/CM2Walki/steamcmd updated the base image from buster to bullseye in May and therefor all machines which are on lower kernel versions (like the Synology NAS machines with 4.4.180+) freeze while starting the server. 

The solution would be to provide a image with Debian 10 like [valheim](https://github.com/lloesche/valheim-server-docker) did.

**Comment by martynvdijke** [comment] 2022-11-28 20:54
I am having the same issues, while I run archlinux with kernel 6.0.10, so I dont think its kernel related ?
Any fix for this issues?

**Comment by wolveix** [comment] 2022-11-28 21:01
Hey guys, thanks for the details and sorry to hear that others are affected by this same issue. I'm still unable to reproduce this myself, so I'm going to spin up a few different distros to see if I can get to the bottom of this

**Comment by martynvdijke** [comment] 2022-11-28 21:11
Maybe should have put that in my comment put I get:

```
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
src/tier0/threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x587f5fd0/0x0xf7697b'
```

**Comment by Selfmade-RuLeZ** [comment] 2022-11-28 21:27
Yeah, this is another error @martynvdijke 

Your Docker Container got no connection to the steam server as the SteamCMD calls for a network connection. 

@wolveix I would be able to try it but everytime it goes into the `{"log":"src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.\n","stream":"stdout","time":"2022-11-14T10:50:16.84767347Z"}` state, my NAS is freezing and will only restart after a hard reset. So I use my Proxmox-Server now for the server and it works well there.

**Comment by zanettibo** [comment] 2022-12-03 12:25
Actualy, it looks like it's a incompatibility issue on steam-for-linux image between debian 11 base image on older kernel verion : 
https://github.com/ValveSoftware/steam-for-linux/issues/8083

I successfuly manage to fix it by rebuilding a older steamcmd image and source it here : 

```
git clone https://github.com/CM2Walki/steamcmd.git
cd steamcmd
git co 56ed323
cd buster-root
sed -i -e '/noninteractive/! s/=.* \\/ \\/' Dockerfile
docker build -t steamcmd:buster-root .
cd ../../

git clone https://github.com/wolveix/satisfactory-server
cd satisfactory-server
sed -i -e 's/cm2network\/steamcmd:root/steamcmd:buster-root/' Dockerfile
docker build -t satisfactory-server:buster .
```

and then, just use `satisfactory-server:buster` image

**Comment by carrierfry** [comment] 2022-12-07 14:08
@zanettibo Thank you so much. This just worked!

**Comment by wolveix** [comment] 2022-12-07 14:16
@zanettibo thank you for your contribution! And thank you for testing @carrierfry. I'm going to look into this and figure out a solution for now.

**Comment by wolveix** [comment] 2022-12-07 21:15
@zanettibo I've just pushed a commit that _should_ address this issue. Would you mind trying it?

**Comment by zanettibo** [comment] 2022-12-07 21:34
Works perfectly GG @wolveix :mechanical_arm: 

maybe it shoud be better to build two images, on from `steamcmd/steamcmd:ubuntu-18` with a specific tag and another one from `steamcmd/steamcmd:latest` for your latest version.

Here we are talking about keeping compatibility with old docker hosts (on debian 10). It's a little bit wiered to get stuck in the past  for this specific usecase ;) 

If you want I can take some time this weekend to propose a PR

**Comment by wolveix** [comment] 2022-12-07 21:36
@zanettibo I'm glad to hear it! I'm not concerned with having multiple images at this time (given that any changes to the latest `steamcmd` image are unlikely to have any real impact on this project). But should we choose to explore that avenue in the future, I'll be sure to let you know! :)

**Closed** 2022-12-07 21:36 UTC
