### ISSUE TITLE
Clients can't connect (v5) due to "Version mismatch detected between game and server"

### ISSUE THREAD

**Issue by jp495** [wolveix/satisfactory-server#87] opened 2021-11-17 05:01 UTC
```log
Version mismatch detected between game and server. Game Version: 172651, Server Version: 172183
```

I'm not sure why this seems to be running so far behind the version my friends are running (v5 Experimental). Based on what I see in the container logs I assume it's using the latest version, but I can't figure out why friends see this error when they try to join.

Any thoughts? (I'm super new to Artifactory -- I'm just hosting this for friends)

Log snippets that seemed potentially relevant:
```log
Setting max players to 8
Experimental flag is set. Experimental will be downloaded instead of Early Access.
Checking available space...169GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (76 of 54,186 KB)...
[  0%] Downloading update (3,609 of 54,186 KB)...
. . .
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
. . .
[2021.11.17-04.46.38:480][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.11.17-04.46.38:480][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.11.17-04.46.38:480][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
. . .
[2021.11.17-04.46.38:482][  0]LogInit: OnPostEngineInit has been broadcasted successfully.
[2021.11.17-04.46.38:484][  0]LogInit: Display: Starting Game.
```

`docker-compose.yml`:
```yaml
version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - '/docker-volumes/satisfactory_server:/config'
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - STEAMBETA=true  # Runs experimental branch if `true`
      - SERVERBEACONPORT=15000
      - SERVERGAMEPORT=7777
      - SERVERIP=0.0.0.0
      - SERVERQUERYPORT=15777
    restart: unless-stopped
```

**Comment by wolveix** [comment] 2021-11-17 10:52
Hey! The server will update on container start, so you probably just need to restart it

**Comment by jp495** [comment] 2021-11-18 03:07
Hmm. Appreciate the response, but I didn't have any luck. Those logs were from a fresh restart (`docker-compose down`, `docker pull wolveix/satisfactory-server`, `docker-compose up -d`).

Regardless, I deleted the container for the hell of it and tried again.

```log
Digest: sha256:21804751c772bbab5095db80c81e7c6543ac15ae1871eff10d376fdfc3aed407
Status: Downloaded newer image for wolveix/satisfactory-server:latest
Creating satisfactory-server ... done
```

User still gets the same error. I'm pretty stumped.

**Comment by Oldsouldier** [comment] 2021-11-19 00:14
Have you tried STEAMBETA=false ? The dedicated servers don't have an experimental track yet as update 5 is required. Not sure if it will be ignored.
Also try deleting your gamefiles folder and redownloading. 

Also there have been version mismatches previously between server and client due to their rapid patch releases. They also had build system issues recently. It might just work itself out.

**Comment by wolveix** [comment] 2021-11-19 00:27
Based on the fact that the reported error mentions that the user version is higher than the server version, I don't think the `STEAMBETA` flag is the issue here. My best guess would be that CSS need to push an update to the server, but I'm not sure and I haven't tested the latest version myself. Can anyone else confirm whether the latest version of the server is working with the latest version of the client?

**Comment by wolveix** [comment] 2021-11-25 19:23
@jp495 could you confirm whether you're still experiencing tbis issue?

**Comment by wolveix** [comment] 2021-11-26 18:24
I believe that this issue was caused by CSS's different release versions as @Oldsouldier mentioned, so I believe that the issue is both out of scope and probably resolved now.

**Closed by wolveix** 2021-11-26 18:24 UTC
