### ISSUE TITLE
New version released today with DLSS breaks server

### ISSUE THREAD

**Issue by ThEWiZ76** [wolveix/satisfactory-server#205] opened 2023-08-23 18:23 UTC
**Describe the Bug**
The release of today (23-8) introduces DLSS support, but the latest version of the docker container does not include it. Stops the server with error
```
Message dialog closed, result: Ok, title: Message, text: Plugin 'DLSS' failed to load because module 'DLSSBlueprint' could not be found
```
**Your Runtime Command or Docker Compose File**
Not needed, worked for several months now, but the image is missing files

**System Specs (please complete the following information):**
Not needed, top notch server, worked like a charm for months.

**Additional Context**
Please add the required files or change the bash script to pull them.

Thanks for making this, saves me a lot of time!

**Comment by ThEWiZ76** [comment] 2023-08-23 18:24
p.s. If there is a workaround to get it in manually it would be fine for me at this time

**Comment by wolveix** [comment] 2023-08-23 18:54
Hey, this is a duplicate of #204

**Closed by wolveix** 2023-08-23 18:54 UTC
