### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by LoganAvatar** [wolveix/satisfactory-server#71] opened 2021-11-03 23:17 UTC
**Describe the Bug**
Dedicated server is failing to start

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
#        image: 'satisfactory-server:test'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - DEBUG=false
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - SKIPUPDATE=false
            - STEAMBETA=true
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/satisfactory/config:/config'
        restart: unless-stopped
```

**System Specs (please complete the following information):**
 - OS: ubuntu LTS

**Additional Context**
Issue workaround here: https://questions.satisfactorygame.com/post/61830560831c852052359b1c

**Comment by wolveix** [comment] 2021-11-03 23:20
Duplicate of #70 and already fixed.

**Closed** 2021-11-03 23:20 UTC
Labels: duplicate

**Comment by LoganAvatar** [comment] 2021-11-03 23:30
oh man! you are too fast (And i suck at setting the title)
